name: Deploy Application Charts
description: "Deploy a application in the k8s cluster via helm."
inputs:
  values_file:
    description: "Local values yaml file"
    required: false
    default: ./deploy/values.local.yaml 
  release_name:
    description: "The release name of the application to be deployed, default value is this repo name"
    required: false
  image_tag_key_path:
    description: "The image tag yaml key path"
    required: false
    default: "image.tag"
  image_tag:
    description: "The image tag of the application to be deployed"
    required: true
  host:
    description: "ssh connect host"
    required: false
    default: deploy.apps.jet.work
  user:
    description: "ssh connect user name"
    required: false
    default: github-deployer
  port:
    description: "ssh connect port"
    required: false
    default: 22
  private_key:
    description: "ssh connect private key"
    required: true
  namespace:
    description: "Kubernetes cluster namespace, supports values: nightly, production and test"
    required: true
  chart_name:
    description: "It is the name of your chart"
    required: false
    default: "application-chart-template"
outputs:
  public_url:
    description: "The public URL for a application deployed on a Kubernetes cluster"
    value: ${{ steps.get-public-url.outputs.public_url }}

runs:
  using: 'composite'
  steps:
    - name: Get repo name and set release name
      shell: bash
      run: |
        REPO_NAME=$(basename ${{ github.repository }})
        REPO_NAME=${REPO_NAME//_/-}
        echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
        echo "RELEASE_NAME=$([ -n "${{ inputs.release_name }}" ] && echo "${{ inputs.release_name }}" || echo "$REPO_NAME")" >> $GITHUB_ENV

    - name: Verify that the namespace value is production or test
      shell: bash
      run: |
        case ${{ inputs.namespace }} in
          nightly)
          echo "NAMESPACE=nightly" >> $GITHUB_ENV
          ;;
          production)
          echo "NAMESPACE=production" >> $GITHUB_ENV
          ;;
          test)
          echo "NAMESPACE=test" >> $GITHUB_ENV
          ;;
          *)
          echo "ERROR: The namespace value only supports nightly, production and test!"
          exit 1
          ;;
        esac

    - name: Deploy the application
      shell: bash
      run: |
        echo "${{ inputs.private_key }}" > private.key && chmod 600 private.key

        cat ${{ inputs.values_file }} <<-END | ssh -i private.key -o "StrictHostKeyChecking=no" ${{ inputs.user }}@${{ inputs.host }} -p ${{ inputs.port }} \
          "helm upgrade --install ${{ env.REPO_NAME }}-${{ env.RELEASE_NAME }} -f - --set ${{ inputs.image_tag_key_path }}=${{ inputs.image_tag }} --namespace ${{env.NAMESPACE }} app-template/${{ inputs.chart_name }}"
        END

    - name: The public URL for a application deployed on a Kubernetes cluster.
      id: get-public-url
      uses: mikefarah/yq@v4
      with:
        cmd: |
          echo "$(yq '.applicationHosts' ${{ inputs.values_file }} || yq '.hosts' ${{ inputs.values_file }})" | while read line; do
            echo $line | awk '{print $2}'
          done
