name: Deploy Frontend Application
description: "Deploy a frontend application in the k8s cluster via helm."
inputs:
  values_file:
    description: "local values yaml file"
    required: false
    default: ./deploy/values.local.yaml 
  release_name:
    description: "deploy application name"
    required: false
  image_tag:
    description: "deploy application tag"
    required: true
  host:
    description: "ssh connect host"
    required: false
    default: deploy.apps.jet.work
  user:
    description: "ssh connect user name"
    required: false
    default: github-deployer
  port:
    description: "ssh connect port"
    required: false
    default: 22
  private_key:
    description: "ssh connect  priviate key"
    required: true
  namespace:
    description: "Kubernetes cluster namespace, supports two values: production and test"
    required: false
    default: test
outputs:
  public_url:
    description: "The public URL for a frontend application deployed on a Kubernetes cluster"
    value: ${{ steps.domain_name.outputs.domain_name }}

runs:
  using: 'composite'
  steps:
    - name: Get repo name
      shell: bash
      run: |
        REPO_NAME=$(basename ${{ github.repository }})
        echo "RELEASE_NAME=$([ -n "${{ inputs.release_name }}" ] && echo "${{ inputs.release_name }}" || echo "$REPO_NAME")" >> $GITHUB_ENV

    - name: Deploy the frontend application
      shell: bash
      run: |
        echo ${{ inputs.private_key }} | base64 -d > private.key && chmod 600 private.key

        ssh -i private.key -o "StrictHostKeyChecking=no" ${{ inputs.user }}@${{ inputs.host }} -p ${{ inputs.port }} \
          "helm repo add --force-update app-template https://Byzanteam.github.io/helm-charts"

        scp -i private.key -o "StrictHostKeyChecking=no" -P ${{ inputs.port }} ${{ inputs.values_file }} ${{ inputs.user }}@${{ inputs.host }}:/tmp/${{ env.RELEASE_NAME }}.values.yaml

        ssh -i private.key -o "StrictHostKeyChecking=no" ${{ inputs.user }}@${{ inputs.host }} -p ${{ inputs.port }} \
          "helm upgrade --install ${{ env.RELEASE_NAME }} \
            -f /tmp/${{ env.RELEASE_NAME }}.values.yaml \
            --set image.tag=${{ inputs.image_tag }} \
            --namespace ${{ inputs.namespace }} --create-namespace \
            app-template/application-chart-template"

    - name: The public URL for a frontend application deployed on a Kubernetes cluster.
      id: public_url
      shell: bash
      run: |
        echo "public_url<<EOF" >> $GITHUB_OUTPUT
        echo "$(yq '.applicationHosts' ${{ inputs.values_file }})" | while read line; do
          echo $line | awk '{print $2}' >> $GITHUB_OUTPUT
        done
        echo "EOF" >> $GITHUB_OUTPUT

