name: 'Registry Login'
description: 'GitHub Action to login image registry'
author: 'Byzanteam'

inputs:
  registry-info:
    description: "Image registry info. Each registry should be formatted as follows: `${hostname},${namespace},${username},${password}`."
    required: true
outputs:
  hostname:
    description: 'Image registry hostname.'
  ns:
    description: 'Image registry namespace.'

runs:
  using: 'node20'
  main: 'dist/index.js'
  post: 'dist/index.js'
