name: 'Registry Login'
description: 'GitHub Action to login image registry'
author: 'Byzanteam'

inputs:
  registry-info:
    description: 'Image registry info. Include registry server address, namespace, username and password.'
    required: true
outputs:
  registry-hostname:
    description: 'Image registry hostname.'
  registry-namespace:
    description: 'Image registry namespace.'

runs:
  using: 'docker'
  image: 'hayd/deno-lambda'
  with:
    entrypoint: 'src/main.ts'
