name: Multi Platform Buildx
description: "Setup multi platform buildx."

runs:
  using: 'composite'
  steps:
    - name: Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver: kubernetes
        platforms: linux/amd64
        driver-opts: namespace=arc-runners,nodeselector=kubernetes.io/arch=amd64
        append: |
          - platforms: linux/arm64
            driver-opts:
              - namespace=arc-runners
              - nodeselector=kubernetes.io/arch=arm64
