name: Uninstall helm release
description: "This action is used to uninstall the helm release"
inputs:
  release_name:
    description: "Deployed application release name"
    required: false
  k8s_apiserver:
    description: "K8s apiserver address"
    required: false
    default: https://10.64.0.43:6443
  k8s_token:
    description: "K8s apiserver auth token"
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Release name
      id: release_name
      shell: bash
      run: |
        REPO_NAME=$(basename ${{ github.repository }})
        echo "release=$([ -n "${{ inputs.release_name }}" ] && \
          echo "${{ inputs.release_name }}" || \
          echo "$REPO_NAME-${{ github.event.pull_request.number }}")" >> $GITHUB_OUTPUT

    - name: Uninstall the helm release
      shell: bash
      run: |
        helm uninstall ${{ steps.release_name.outputs.release }} \
          --kube-token ${{ inputs.k8s_token }} \
          --kube-apiserver ${{ inputs.k8s_apiserver }} \
          --namespace test \
          --kube-insecure-skip-tls-verify \
