name: Deploy
description: Deploy to the server
inputs:
  deploy_host:
    description: ssh host
    required: true
  deploy_port:
    description: ssh port, default is 22
    required: true
    default: 22
  deploy_user:
    description: ssh user
    required: true
  deploy_to:
    description: deploy-to directory
    required: true
  private_key:
    description: content of ssh private key. ex raw content of ~/.ssh/id_rsa
    required: true
  image_name:
    description: upgrade image name
    required: true
  image_version:
    description: upgrade image version
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
