name: Deploy
description: Deploy to the server
inputs:
  deploy-host:
    description: ssh host
    required: true
  deploy-port:
    description: ssh port, default is 22
    required: true
    default: 22
  deploy-user:
    description: ssh user
    required: true
  deploy-to:
    description: deploy-to directory
    required: true
  private-key:
    description: content of ssh private key. ex raw content of ~/.ssh/id_rsa
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    DEPLOY_HOST: ${{ inputs.deploy-host }}
    DEPLOY_PORT: ${{ inputs.deploy-port }}
    DEPLOY_USER: ${{ inputs.deploy-user }}
    DEPLOY_TO: ${{ inputs.deploy-to }}
    PRIVATE_KEY: ${{ inputs.private-key }}
