name: Bump mix project version

inputs:
  workflow-actor:
    required: true
    type: string
  repository:
    required: true
    type: string
  release-kind:
    description: 'Kind of version bump, one of: major, minor, patch.'
    type: string
    required: true
  gh-token:
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        path: 'main'
    - uses: actions/checkout@v4
      with:
        repository: 'Byzanteam/jet-actions'
        path: 'jet-actions'
        sparse-checkout: |
          denoified-actions/

    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x

    - name: Create PR
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.gh-token }}
        GH_WORKFLOW_ACTOR: ${{ inputs.workflow-actor }}
        GH_REPOSITORY: ${{ inputs.repository }}
        RELEASE_KIND: ${{ inputs.release-kind }}
      working-directory: "./main"
      run: |
        ../jet-actions/denoified-actions/elixir/bump_version/main.ts
