name: Setup Elixir
description: Setup a specific version of Erlang/OTP and Elixir
inputs:
  fetch-depth:
    description: Number of commits to fetch
    default: 1
  submodules:
    description: Whether to checkout submodules
    default: false
  elixir-version:
    description: Version range or exact version of Elixir
    required: true
  otp-version:
    description: Version range or exact version of Erlang/OTP
    required: true
  cache-path:
    description: Paths that should be cached
    default: |
      _build
      deps
outputs:
  cache-hit:
    description: A boolean value to indicate an exact cache was found
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        submodules: ${{ inputs.submodules }}
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ inputs.otp-version }}
        elixir-version: ${{ inputs.elixir-version }}
    - id: cache
      uses: actions/cache@v4
      with:
        path: ${{ inputs.cache-path }}
        key: mix-${{ runner.os }}-${{ inputs.otp-version }}-${{ inputs.elixir-version }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          mix-${{ runner.os }}-${{ inputs.otp-version }}-${{ inputs.elixir-version }}-
    - run: echo "cache-hit=${{ steps.cache.outputs.cache-hit }}" >> $GITHUB_OUTPUT
      shell: bash
