name: 'FE Build Image'
description: Build and push front-end image for deploy
inputs:
  context:
    description: "Build's context is the set of files located in the specified PATH or URL"
    required: false
    default: .
  dockerfile:
    description: path to Dockerfile
    required: false
    default: ./deploy/Dockerfile
  build_args:
    description: List of build-time variables
    required: false
  package_file:
    description: The package.json file
    default: package.json
    required: false

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Get APP Info
      uses: byzanteam/jet-actions/fe-get-app-info@main
      with:
        package_file: ${{ inputs.package_file }}
      id: get-app-info

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        build-args: |
          APP_VSN=${{ steps.get-app-info.outputs.version }}
          APP_NAME=${{ steps.get-app-info.outputs.name }}
          SOURCE_REPO_URL=${{ github.repositoryUrl }}
          SOURCE_SHA=${{ github.sha }}
          ${{ inputs.build_args }}
        push: true
        tags: |
          ghcr.io/Byzanteam/${{ steps.get-app-info.outputs.name }}:${{ steps.get-app-info.outputs.version }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
