name: Rollout
description: Restart resources to rollout
inputs:
  deploy_host:
    description: ssh host
    required: true
  deploy_port:
    description: ssh port, default is 22
    required: true
    default: 22
  deploy_user:
    description: ssh user
    required: true
  private_key:
    description: content of ssh private key. ex raw content of ~/.ssh/id_rsa
    required: true
  resource:
    description: kubectl set image `$resource` $container=$registry/$image:$tag
    required: true
  container:
    description: kubectl set image $resource `$container`=$registry/$image:$tag
    required: true
  registry:
    description: kubectl set image $resource $container=`$registry`/$image:$tag
    required: true
  image:
    description: kubectl set image $resource $container=$registry/`$image`:$tag
    required: true
  tag:
    description: kubectl set image $resource $container=$registry/$image:`$tag`
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
