name: Spell check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  spell-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Spell-check
        uses: crate-ci/typos@master
