name: front deploy
description: "前端应用部署 actions, 通过 helm chart 在 kubernetes 集群中部署应用"
inputs:
  values_file:
    description: "local values yaml file"
    required: false
    default: ./deploy/values.local.yaml 
  release_name:
    description: "deploy application name"
    required: true
  image_tag:
    description: "deploy application tag"
    required: true
  host:
    description: "ssh connect host"
    required: true
  user:
    description: "ssh connect user name"
    required: true
  port:
    description: "ssh connect port"
    required: false
    default: 22
  private_key:
    description: "ssh connect  priviate key"
    required: true
  repository_password:
    description: "Password for logging in to the repository"
    required: true

runs:
  using: 'composite'
  steps:
    - name: get-name
      shell: bash
      run: |
        echo "REPO_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV

    - name: Deploy front app
      shell: bash
      run: |
        echo ${{ inputs.private_key }} | base64 -d > private.key && chmod 600 private.key

        ssh -i private.key -o "StrictHostKeyChecking=no" ${{ inputs.user }}@${{ inputs.host }} -p ${{ inputs.port }} \
          "helm repo add --force-update app-template https://Byzanteam.github.io/helm-charts"

        scp -i private.key -o "StrictHostKeyChecking=no" -P ${{ inputs.port }} ${{ inputs.values_file }} ${{ inputs.user }}@${{ inputs.host }}:/tmp/${{ env.REPO_NAME }}.values.yaml

        ssh -i private.key -o "StrictHostKeyChecking=no" ${{ inputs.user }}@${{ inputs.host }} -p ${{ inputs.port }} \
          "helm upgrade --install ${{ inputs.release_name }} app-template/application-chart-template -f /tmp/${{ env.REPO_NAME }}.values.yaml --set image.tag=${{ inputs.image_tag }} --set imageCredentials.password=${{ inputs.repository_password }}"

